### ISSUE TITLE
Bad notification for startForeground

### ISSUE THREAD

**Issue by aotourdeveloper1** [transistorsoft/capacitor-background-geolocation#105]
I am integrating the plugin but when starting the geolocation it throws me this error.

![image](https://user-images.githubusercontent.com/115663529/195432062-500ee7c7-7fc2-4a4d-9a78-30ca8f2747f1.png)

--console android stududio text--

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.aotour.driver, PID: 7856
    android.app.RemoteServiceException: Bad notification for startForeground
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by christocracy** [comment]
I told you in the email:  "**do not** ignore the issue template."

There is even a **WARNING** at the top.

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

 Provide a general summary of the issue in the Title above. Please use syntax highlighting when posting code. Wrap your code in three(3) back ticks (```) . Thank you.
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* Device OS version:
* Device manufacturer / model:
* XCode version:
* Capacitor info (`npx cap doctor`)
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
