### ISSUE TITLE
Android Build Failed to list versions for com.transistorsoft:tsbackgroundfetch

### ISSUE THREAD

**Issue by aliexalter** [transistorsoft/capacitor-background-geolocation#172]
## Your Environment
* Plugin version: @transistorsoft/capacitor-background-geolocation@5.0.0 capacitor-background-fetch@5.0.0
* Platform: Android
* Device OS version: Simulator Pixel 4 API 31
* Device manufacturer / model: Simulator
* XCode version: not using for iOS
* Capacitor info (`npx cap doctor`)
Latest Dependencies:

  @capacitor/cli: 5.0.3
  @capacitor/core: 5.0.3
  @capacitor/android: 5.0.3
  @capacitor/ios: 5.0.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.0.3
  @capacitor/core: 5.0.3
  @capacitor/android: 5.0.3
* Plugin config provided to `#ready`:
```/// Step 2:  Ready the plugin.
    BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 5,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
    }).then((state) => {
      // BackgroundGeolocation is now ready to use.
      this.ready = true;
    });
```

## Expected Behavior
It should compile on Android Simulator and give beep sound.

## Actual Behavior
Project start building on Android Studio and in the middle build failed saying Failed to list versions for com.transistorsoft:tsbackgroundfetch

## Steps to Reproduce

1. Create ionic capacitor app
2. Install the plugin as mention in document
3. Setup Android as mention in documentation
4. Run the project in Android Studio Flamingo | 2022.2.1 Patch 1 which has AGP 8.0.2 , Gradle 7.0.2, Java version 17

## Context
Trying to run the project on Simulator through Android Studio

## Debug logs

<details>
	<summary>Logs</summary>

```FAILURE: Build completed with 10 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:+.
     Required by:
         project :app > project :transistorsoft-capacitor-background-fetch
      > Failed to list versions for com.transistorsoft:tsbackgroundfetch.
         > Unable to load Maven meta-data from https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml.
            > Could not GET 'https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'.
               > Connect to developer.huawei.com:443 [developer.huawei.com/59.103.93.179, developer.huawei.com/59.103.93.178] failed: Connect timed out
   > Could not resolve com.huawei.hms:location:6.9.0.300.
     Required by:
         project :app > project :transistorsoft-capacitor-background-geolocation
      > Skipped due to earlier error

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:checkDebugAarMetadata'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to developer.huawei.com:443 [developer.huawei.com/59.103.93.179, developer.huawei.com/59.103.93.178] failed: Connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:170)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:146)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.executeGetOrHead(HttpClientHelper.java:135)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performRequest(HttpClientHelper.java:105)
	... 157 more
Caused by: java.net.SocketTimeoutException: Connect timed out
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 169 more
Cause 2: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.huawei.hms:location:6.9.0.300.
Required by:
    project :app > project :transistorsoft-capacitor-background-geolocation
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Skipped due to earlier error

==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mapDebugSourceSetPaths'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:+.
     Required by:
         project :app > project :transistorsoft-capacitor-background-fetch
      > Failed to list versions for com.transistorsoft:tsbackgroundfetch.
         > Unable to load Maven meta-data from https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml.
            > Could not GET 'https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'.
               > Connect to developer.huawei.com:443 [developer.huawei.com/59.103.93.179, developer.huawei.com/59.103.93.178] failed: Connect timed out
   > Could not resolve com.huawei.hms:location:6.9.0.300.
     Required by:
         project :app > project :transistorsoft-capacitor-background-geolocation
      > Skipped due to earlier error

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:mapDebugSourceSetPaths'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	...
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:170)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:146)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.executeGetOrHead(HttpClientHelper.java:135)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performRequest(HttpClientHelper.java:105)
	... 157 more
Caused by: java.net.SocketTimeoutException: Connect timed out
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 169 more
Cause 2: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.huawei.hms:location:6.9.0.300.
Required by:
    project :app > project :transistorsoft-capacitor-background-geolocation
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Skipped due to earlier error

==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:+.
     Required by:
         project :app > project :transistorsoft-capacitor-background-fetch
      > Failed to list versions for com.transistorsoft:tsbackgroundfetch.
         > Unable to load Maven meta-data from https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml.
            > Could not GET 'https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'.
               > Connect to developer.huawei.com:443 [developer.huawei.com/59.103.93.179, developer.huawei.com/59.103.93.178] failed: Connect timed out
   > Could not resolve com.huawei.hms:location:6.9.0.300.
     Required by:
         project :app > project :transistorsoft-capacitor-background-geolocation
      > Skipped due to earlier error

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:mergeDebugResources'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	...
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:170)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:146)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.executeGetOrHead(HttpClientHelper.java:135)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performRequest(HttpClientHelper.java:105)
	... 157 more
Caused by: java.net.SocketTimeoutException: Connect timed out
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 169 more
Cause 2: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.huawei.hms:location:6.9.0.300.
Required by:
    project :app > project :transistorsoft-capacitor-background-geolocation
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Skipped due to earlier error

==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:+.
     Required by:
         project :app > project :transistorsoft-capacitor-background-fetch
      > Failed to list versions for com.transistorsoft:tsbackgroundfetch.
         > Unable to load Maven meta-data from https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml.
            > Could not GET 'https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'.
               > Connect to developer.huawei.com:443 [developer.huawei.com/59.103.93.179, developer.huawei.com/59.103.93.178] failed: Connect timed out
   > Could not resolve com.huawei.hms:location:6.9.0.300.
     Required by:
         project :app > project :transistorsoft-capacitor-background-geolocation
      > Skipped due to earlier error

	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:170)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:146)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.executeGetOrHead(HttpClientHelper.java:135)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performRequest(HttpClientHelper.java:105)
	... 157 more
Caused by: java.net.SocketTimeoutException: Connect timed out
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 169 more
Cause 2: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.huawei.hms:location:6.9.0.300.
Required by:
    project :app > project :transistorsoft-capacitor-background-geolocation
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Skipped due to earlier error

==============================================================================

5: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':transistorsoft-capacitor-background-geolocation:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':transistorsoft-capacitor-background-geolocation:debugCompileClasspath'.
   > Could not resolve com.huawei.hms:location:6.9.0.300.
     Required by:
         project :transistorsoft-capacitor-background-geolocation
      > Skipped due to earlier error

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':transistorsoft-capacitor-background-geolocation:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	...
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.huawei.hms:location:6.9.0.300.
Required by:
    project :transistorsoft-capacitor-background-geolocation
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Skipped due to earlier error

==============================================================================

6: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:+.
     Required by:
         project :app > project :transistorsoft-capacitor-background-fetch
      > Failed to list versions for com.transistorsoft:tsbackgroundfetch.
         > Unable to load Maven meta-data from https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml.
            > Could not GET 'https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'.
               > Connect to developer.huawei.com:443 [developer.huawei.com/59.103.93.179, developer.huawei.com/59.103.93.178] failed: Connect timed out
   > Could not resolve com.huawei.hms:location:6.9.0.300.
     Required by:
         project :app > project :transistorsoft-capacitor-background-geolocation
      > Skipped due to earlier error

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:mergeDebugAssets'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	...
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:170)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:146)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.executeGetOrHead(HttpClientHelper.java:135)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performRequest(HttpClientHelper.java:105)
	... 157 more
Caused by: java.net.SocketTimeoutException: Connect timed out
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 169 more
Cause 2: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.huawei.hms:location:6.9.0.300.
Required by:
    project :app > project :transistorsoft-capacitor-background-geolocation
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Skipped due to earlier error

==============================================================================

7: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:desugarDebugFileDependencies'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:+.
     Required by:
         project :app > project :transistorsoft-capacitor-background-fetch
      > Failed to list versions for com.transistorsoft:tsbackgroundfetch.
         > Unable to load Maven meta-data from https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml.
            > Could not GET 'https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'.
               > Connect to developer.huawei.com:443 [developer.huawei.com/59.103.93.179, developer.huawei.com/59.103.93.178] failed: Connect timed out
   > Could not resolve com.huawei.hms:location:6.9.0.300.
     Required by:
         project :app > project :transistorsoft-capacitor-background-geolocation
      > Skipped due to earlier error

==============================================================================

8: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:+.
     Required by:
         project :app > project :transistorsoft-capacitor-background-fetch
      > Failed to list versions for com.transistorsoft:tsbackgroundfetch.
         > Unable to load Maven meta-data from https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml.
            > Could not GET 'https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'.
               > Connect to developer.huawei.com:443 [developer.huawei.com/59.103.93.179, developer.huawei.com/59.103.93.178] failed: Connect timed out
   > Could not resolve com.huawei.hms:location:6.9.0.300.
     Required by:
         project :app > project :transistorsoft-capacitor-background-geolocation
      > Skipped due to earlier error

==============================================================================

9: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:+.
     Required by:
         project :app > project :transistorsoft-capacitor-background-fetch
      > Failed to list versions for com.transistorsoft:tsbackgroundfetch.
         > Unable to load Maven meta-data from https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml.
            > Could not GET 'https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'.
               > Connect to developer.huawei.com:443 [developer.huawei.com/59.103.93.179, developer.huawei.com/59.103.93.178] failed: Connect timed out
   > Could not resolve com.huawei.hms:location:6.9.0.300.
     Required by:
         project :app > project :transistorsoft-capacitor-background-geolocation
      > Skipped due to earlier error

==============================================================================

10: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:+.
     Required by:
         project :app > project :transistorsoft-capacitor-background-fetch
      > Failed to list versions for com.transistorsoft:tsbackgroundfetch.
         > Unable to load Maven meta-data from https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml.
            > Could not GET 'https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'.
               > Connect to developer.huawei.com:443 [developer.huawei.com/59.103.93.179, developer.huawei.com/59.103.93.178] failed: Connect timed out
   > Could not resolve com.huawei.hms:location:6.9.0.300.
     Required by:
         project :app > project :transistorsoft-capacitor-background-geolocation
      > Skipped due to earlier error

==============================================================================

BUILD FAILED in 3m 12s
```

</details>

**Comment by aliexalter** [comment]
It worked using VPN it downloads some files from https://developer.huawei.com/repo/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml. use for compilation

**Comment by christocracy** [comment]
You have a problem in your android/build.gradle.

See the Android Setup Instructions and follow them exactly.

**Comment by aliexalter** [comment]
I reinstall android studio latest version and its working now thanks.
