### ISSUE TITLE
IncompatibleClassChangeError after upgrade to Capacitor 5

### ISSUE THREAD

**Issue by Ionaru** [transistorsoft/capacitor-background-geolocation#173]
## Your Environment
* Plugin version: 5.0.0
* Platform: Android
* Device OS version: 13
* Device manufacturer / model: Pixel 6 (emulated)
* XCode version: n/a
* Capacitor info (`npx cap doctor`)
  * error is due to https://github.com/ionic-team/capacitor/issues/3749, a .java file gives OK 👌
```
[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 5.0.3
  @capacitor/core: 5.0.3
  @capacitor/android: 5.0.3
  @capacitor/ios: 5.0.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.0.3
  @capacitor/core: 5.0.3
  @capacitor/android: 5.0.3

[error] Main activity file (MainActivity.java) is missing in
        C:\Users\name\Projects\port-alert-mobile\android\app\src\main\java\com\portbase\portalert
```
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 10,
      // Activity Recognition
      stopTimeout: 5,
      // Application config
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_INFO,
      stopOnTerminate: true,
      startOnBoot: false,
}
```

## Expected Behavior
The app starts and begins watching the user's position.

## Actual Behavior
The app crashes with the error:
```
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected
```

## Steps to Reproduce
I've not been unable to reproduce this error in an isolated environment, but as far as I know we're not doing anything exotic that could cause this problem. Hopefully a person with more in-depth Android knowledge can point to the root cause of the error.

## Context
I had just upgraded Capacitor and the plugins to v5

Maybe related to https://stackoverflow.com/questions/74085319/class-was-expected-declaration-of-com-google-android-gms-location-fusedlocatio. But my `variables.gradle` has `googlePlayServicesLocationVersion = '20.0.0'`.

In `android/app/build/outputs/logs/manifest-merger-debug-report.txt` I see this line:
```
MERGED from [com.google.android.gms:play-services-location:21.0.1]
```
but a clean app has this line:
```
MERGED from [com.google.android.gms:play-services-location:20.0.0]
```

What causes this? Does another plugin bump `play-services-location` to `21.0.1`?

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
[c.t.l.l.TSLocationManager watchPosition] 
  🎾  watchPosition: ON
Shutting down VM
FATAL EXCEPTION: main
Process: com.portbase.portalert, PID: 6127
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~I8LPZotKG3KMzFwH8qm_Yw==/com.portbase.portalert-AKL08U-jjQlrX2WzfkpXCg==/base.apk)
	at com.transistorsoft.xms.g.location.FusedLocationProviderClient.requestLocationUpdates(Unknown Source:70)
	at com.transistorsoft.locationmanager.location.TSWatchPositionRequest.startUpdatingLocation(Unknown Source:88)
	at com.transistorsoft.locationmanager.location.TSWatchPositionRequest$a.onPermissionGranted(Unknown Source:36)
	at com.transistorsoft.locationmanager.util.c$f.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[c.t.l.a.BackgroundGeolocation$w0 uncaughtException] 
  ‼️  Uncaught Exception: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~I8LPZotKG3KMzFwH8qm_Yw==/com.portbase.portalert-AKL08U-jjQlrX2WzfkpXCg==/base.apk)
{"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":0,"backgroundPermissionRationale":{"title":"Allow {applicationName} to access this device's location even when closed or not in use?","message":"[CHANGEME] This app collects location data for FEATURE X and FEATURE Y.","positiveAction":"Change to \"{backgroundPermissionOptionLabel}\"","negativeAction":""},"batchSync":false,"configUrl":"","debug":false,"deferTime":0,"desiredAccuracy":-1,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableProviderChangeRecord":false,"disableStopDetection":false,"distanceFilter":10,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":-1,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.portbase.portalert.BackgroundGeolocationHeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":3,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","channelId":"","smallIcon":"","largeIcon":"","priority":0,"sticky":false,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":false,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":true,"stopTimeout":5,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"","useSignificantChangesOnly":false,"enabled":false,"schedulerEnabled":false,"trackingMode":1,"odometer":0,"isFirstBoot":false,"didLaunchInBackground":false,"didDeviceReboot":false}
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~I8LPZotKG3KMzFwH8qm_Yw==/com.portbase.portalert-AKL08U-jjQlrX2WzfkpXCg==/base.apk)
	at com.transistorsoft.xms.g.location.FusedLocationProviderClient.requestLocationUpdates(Unknown Source:70)
	at com.transistorsoft.locationmanager.location.TSWatchPositionRequest.startUpdatingLocation(Unknown Source:88)
	at com.transistorsoft.locationmanager.location.TSWatchPositionRequest$a.onPermissionGranted(Unknown Source:36)
	at com.transistorsoft.locationmanager.util.c$f.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

</details>

**Comment by Ionaru** [comment]
I think `@capacitor/geolocation` versions 5.0.0 and above require `play-services-location:21.0.1` by default and that needs to be overridden with the variable `playServicesLocationVersion` (not `googlePlayServicesLocationVersion` that `capacitor-background-geolocation` uses).

The problem is that `@capacitor/geolocation@5` is not compatible with `play-services-location:20.0.0`.

**Comment by christocracy** [comment]
Google made a breaking change in 21.0.1.

All plug-ins must be aligned to googlePlayServicesLocationVersion.

When *one* plug-in pulls in 21+, they all must.

**Comment by Ionaru** [comment]
> When one plug-in pulls in 21+, they all must.

That's unfortunate. 

As a solution I've now removed `@capacitor/geolocation`, that seems to work.

**Comment by christocracy** [comment]
They can both be aligned.

Anyway, there’s nothing @capacitor/geolocation does that this plug-in doesn’t do.

**Comment by gianlazz** [comment]
I also encountered this exact same issue and resolved it by setting `googlePlayServicesLocationVersion = '21.0.1'` which seems to be working with `"@transistorsoft/capacitor-background-geolocation": "^5.0.0",`

**Comment by christocracy** [comment]
Yes, Google made a breaking change with their location api.  It’s a well known issue throughout the entire Android developer ecosystem, resolved simply by aligning every plug-in that accesses play-services-location api to the same version.

this is documented in the plug-in CHANGELOG.
