### ISSUE TITLE
capacitor-background-geolocation and @capacitor/geolocation 5.0.0 in one project

### ISSUE THREAD

**Issue by qidulak** [transistorsoft/capacitor-background-geolocation#188]
## Your Environment
* Plugin version: 5.0.0
* Platform: Android
* Device OS version: 12
* Device manufacturer / model: Huavei P30 Pro

## Actual Behavior
 Project uses both capacitor-background-geolocation plugin and @capacitor/geolocation. After update to capacitor 5. Project started crashing with message ```java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms```

## Steps to Reproduce
1. Download version 5.0.0 frim github. Add ``` "@capacitor/geolocation": "^5.0.0", ``` to dependencies in /example/angular/package.json
2. Build project and debug on android device
3. Project will crassh after initial load

## Debug logs

-->
<details>
	<summary>Logs</summary>

```2023-08-24 14:27:08.671  5685-5753  Capacitor               com...ckgroundgeolocation.capacitor  D  Handling local request: http://localhost/101.js
2023-08-24 14:27:08.671  5685-5685  Capacitor/Plugin        com...ckgroundgeolocation.capacitor  V  To native (Capacitor plugin): callbackId: 68604108, pluginId: BackgroundGeolocation, methodName: stop
2023-08-24 14:27:08.671  5685-5685  Capacitor               com...ckgroundgeolocation.capacitor  V  callback: 68604108, pluginId: BackgroundGeolocation, methodName: stop, methodData: {}
2023-08-24 14:27:08.673  5685-5685  Capacitor/Plugin        com...ckgroundgeolocation.capacitor  V  To native (Capacitor plugin): callbackId: 68604109, pluginId: Preferences, methodName: set
2023-08-24 14:27:08.673  5685-5685  Capacitor               com...ckgroundgeolocation.capacitor  V  callback: 68604109, pluginId: Preferences, methodName: set, methodData: {"key":"page","value":"home"}
2023-08-24 14:27:08.679  5685-5752  Capacitor               com...ckgroundgeolocation.capacitor  D  Handling local request: http://localhost/assets/icon/favicon.png
2023-08-24 14:27:08.685  5685-5685  Capacitor/Console       com...ckgroundgeolocation.capacitor  I  File: http://localhost/ - Line 281 - Msg: undefined
2023-08-24 14:27:08.691  5685-5809  QarthLog                com...ckgroundgeolocation.capacitor  I  [PatchStore] createDisableExceptionQarthFile
2023-08-24 14:27:08.691  5685-5809  QarthLog                com...ckgroundgeolocation.capacitor  I  [PatchStore] create disable file for com.transistorsoft.backgroundgeolocation.capacitor uid is 10305
2023-08-24 14:27:08.693  5685-5809  AndroidRuntime          com...ckgroundgeolocation.capacitor  E  FATAL EXCEPTION: pool-2-thread-3
                                                                                                    Process: com.transistorsoft.backgroundgeolocation.capacitor, PID: 5685
                                                                                                    java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/com.transistorsoft.backgroundgeolocation.capacitor-dWnxiYykN0pm9VSJfP-YwQ==/base.apk)
                                                                                                    	at com.transistorsoft.xms.g.location.FusedLocationProviderClient.removeLocationUpdates(Unknown Source:50)
                                                                                                    	at com.transistorsoft.locationmanager.location.TSLocationManager.removeLocationUpdates(Unknown Source:45)
                                                                                                    	at com.transistorsoft.locationmanager.location.TSLocationManager.stopUpdatingLocation(Unknown Source:0)
                                                                                                    	at com.transistorsoft.locationmanager.location.TSLocationManager.stop(Unknown Source:0)
                                                                                                    	at com.transistorsoft.locationmanager.service.TrackingService.stop(Unknown Source:103)
                                                                                                    	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.c(Unknown Source:2)
                                                                                                    	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.$r8$lambda$oSDeWXxQl1jmikdjYQwff60damw(Unknown Source:0)
                                                                                                    	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$$ExternalSyntheticLambda0.run(Unknown Source:4)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:929)
2023-08-24 14:27:08.719  5685-5738  libEGL                  com...ckgroundgeolocation.capacitor  W  EGLNativeWindowType 0x70df00fe50 disconnect failed
```

</details>

**Comment by christocracy** [comment]
Duplicate #173.  Please search ("*java.lang.IncompatibleClassChangeError*") before posting.
