### ISSUE TITLE
Error after launching app - Found interface com.google.android.gms.location.FusedLocationProviderClient

### ISSUE THREAD

**Issue by hvma411** [transistorsoft/capacitor-background-geolocation#209]
## Your Environment
* Plugin version: 5.2.1
* Platform: Android
* Device OS version: every android versions
* Device manufacturer / model: every device with androiv
* XCode version:
* Capacitor info (`npx cap doctor`):
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/ios: 5.4.2

Installed Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/ios: 5.4.2

[success] iOS looking great! 👌
[success] Android looking great! 👌
```
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
			desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
			reset: true,
			logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
			heartbeatInterval: 60,
			preventSuspend: true,
			debug: false,
			fastestLocationUpdateInterval: 10000,
			stopOnTerminate: false,
			showsBackgroundLocationIndicator: true,
			startOnBoot: true,
			persistMode: BackgroundGeolocation.PERSIST_MODE_ALL,
			extras: {
				...params,
				os,
			},
			headers: {
				'x-api-key': 'some-key',
			},
			params: {
				...params,
				os
			},
			locationAuthorizationRequest: 'Always',
			disableLocationAuthorizationAlert: false,
			url: ApiRoutes.COORDS.updateCoords,
			backgroundPermissionRationale: {
				title: 'Some title',
				message: 'Some message',
				positiveAction: 'Zmień na "{backgroundPermissionOptionLabel}"',
				negativeAction: 'Anuluj'
			},
			autoSync: true,
			batchSync: false,
```

## Expected Behavior

App should not crash
## Actual Behavior
App crashes after accepting locations permissions with error listen below in logs

## Steps to Reproduce

1.
2.
3.
4.

## Context

Changed versions of plugin, looking in google for solution and found some similar issue for flutter plugin of transistorsoft but nothing from there helped me

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
E  FATAL EXCEPTION: pool-8-thread-4
	Process: io.hublock.truck.drive, PID: 11578
	java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~PTCkVZQ2xYO1hddvO3mB2w==/io.hublock.truck.drive-Vg0R_0x-hXMVfmfNb8WFuA==/base.apk)
		at com.transistorsoft.locationmanager.location.SingleLocationRequest.startUpdatingLocation(Unknown Source:129)
		at com.transistorsoft.locationmanager.service.LocationRequestService.handleStartAction(Unknown Source:78)
		at com.transistorsoft.locationmanager.service.LocationRequestService.access$200(Unknown Source:0)
		at com.transistorsoft.locationmanager.service.LocationRequestService$a.run(Unknown Source:62)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
		at java.lang.Thread.run(Thread.java:923)
E  Instabug Caught an Unhandled Exception: java.lang.IncompatibleClassChangeError
	java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~PTCkVZQ2xYO1hddvO3mB2w==/io.hublock.truck.drive-Vg0R_0x-hXMVfmfNb8WFuA==/base.apk)
		at com.transistorsoft.locationmanager.location.SingleLocationRequest.startUpdatingLocation(Unknown Source:129)
		at com.transistorsoft.locationmanager.service.LocationRequestService.handleStartAction(Unknown Source:78)
		at com.transistorsoft.locationmanager.service.LocationRequestService.access$200(Unknown Source:0)
		at com.transistorsoft.locationmanager.service.LocationRequestService$a.run(Unknown Source:62)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
		at java.lang.Thread.run(Thread.java:923)
E  Can't detect ANR because InstabugANRDetector thread was interrupted.
E  Can't detect Fatal Hangs because the app went to the background.
E  InstabugUncaughtExceptionHandler Caught an Unhandled Exception: java.lang.IncompatibleClassChangeError
	java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~PTCkVZQ2xYO1hddvO3mB2w==/io.hublock.truck.drive-Vg0R_0x-hXMVfmfNb8WFuA==/base.apk)
		at com.transistorsoft.locationmanager.location.SingleLocationRequest.startUpdatingLocation(Unknown Source:129)
		at com.transistorsoft.locationmanager.service.LocationRequestService.handleStartAction(Unknown Source:78)
		at com.transistorsoft.locationmanager.service.LocationRequestService.access$200(Unknown Source:0)
		at com.transistorsoft.locationmanager.service.LocationRequestService$a.run(Unknown Source:62)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
		at java.lang.Thread.run(Thread.java:923)
E  CrashReporting InstabugUncaughtExceptionHandler Caught an Unhandled Exception: java.lang.IncompatibleClassChangeError
	java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~PTCkVZQ2xYO1hddvO3mB2w==/io.hublock.truck.drive-Vg0R_0x-hXMVfmfNb8WFuA==/base.apk)
		at com.transistorsoft.locationmanager.location.SingleLocationRequest.startUpdatingLocation(Unknown Source:129)
		at com.transistorsoft.locationmanager.service.LocationRequestService.handleStartAction(Unknown Source:78)
		at com.transistorsoft.locationmanager.service.LocationRequestService.access$200(Unknown Source:0)
		at com.transistorsoft.locationmanager.service.LocationRequestService$a.run(Unknown Source:62)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
		at java.lang.Thread.run(Thread.java:923)
```

</details>

**Comment by christocracy** [comment]
Duplicate #173.  This has been posted many times before.  Please search *before* posting.
