### ISSUE TITLE
Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient'

### ISSUE THREAD

**Issue by subodhmodgil** [transistorsoft/capacitor-background-geolocation#285]
## Your Environment
* Plugin version: 6.1.0
* Platform: Android
* Device OS version: Android 34
* Device manufacturer / model: Emulator
* XCode version: NA
* Capacitor info (`npx cap doctor`)
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
FATAL EXCEPTION: pool-16-thread-2 (Ask Gemini)
Process: com., PID: 3836
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~s3Z8FSmIWKLEONz9sX6GGg==/com..in==/base.apk) at com.transistorsoft.xms.g.location.FusedLocationProviderClient.getLastLocation(Unknown Source:50) at com.transistorsoft.locationmanager.location.TSLocationManager.getLastLocation(Unknown Source:20) at com.transistorsoft.locationmanager.geofence.TSGeofenceManager$d.a(Unknown Source:38) at com.transistorsoft.locationmanager.geofence.TSGeofenceManager$d.$r8$lambda(Unknown Source:0) at com.transistorsoft.locationmanager.geofence.TSGeofenceManager$d$$ExternalSyntheticLambda0.run(Unknown Source:2) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) at java.lang.Thread.run(Thread.java:1012)

## Expected Behavior
Application should not crash while running transistorsoft plugin

## Actual Behavior
Getting error:
 Process: com., PID: 3836
 java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~s3Z8FSmIWKLEONz9sX6GGg==/com..in==/base.apk)

## Steps to Reproduce
1. While using transistorsoft in android

## Context
Getting below error
FATAL EXCEPTION: pool-16-thread-2 (Ask Gemini)
 Process: com., PID: 3836
## Debug logs
<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
FATAL EXCEPTION: pool-16-thread-2 (Ask Gemini)
 Process: com., PID: 3836
 java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~==/com==/base.apk)
```

</details>

**Comment by christocracy** [comment]
Duplicate #173.  This has been posted many times before.  Please search *before* posting.
