### ISSUE TITLE
CocoaPod install fails

### ISSUE THREAD

**Issue by m8xp0w3r** [transistorsoft/capacitor-background-geolocation#62]
## Your Environment
* Plugin version: ^4.4.6 ("@transistorsoft/capacitor-background-fetch": "^0.0.6")
* Platform: iOS
* Device OS version: no device used because pod installation failed
* Device manufacturer / model: no device used because pod installation failed
* XCode version: 13.3
* Pod version: 1.11.3
* Os Version: macOS Monterey 12.3 on a M1 Pro Chip
* Capacitor info (`npx cap doctor`)
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/ios: 3.4.3

[success] iOS looking great! 👌
``` 
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
			locationAuthorizationRequest: 'Always',
			desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
			geofenceModeHighAccuracy: true,
			distanceFilter: 0,
			disableElasticity: true,
			activityType: BackgroundGeolocation.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION,
			locationUpdateInterval: 2000, // Android only
			useSignificantChangesOnly: false,
			preventSuspend: true, // iOS only
			disableMotionActivityUpdates: true,
			heartbeatInterval: 60,
			stopOnTerminate: false,
			//debug
			//debug: true,
			logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE
		}).then((state) => {
			// BackgroundGeolocation is now ready to use.
			this.ready = true;
			this.enabled = state.enabled;
		});
```

## Expected Behavior
The expected behavior is that the plugin is installed correctly after `npx caps sync`.

## Actual Behavior
Pod installation failed when calling `npx caps sync`.

## Steps to Reproduce

1. `ionic start testgeolocation`
2. `cd testgeolocation`
3. `ionic build`
4. `npm install @capacitor/ios`
5. `npx cap add ios`
6. `npm install @transistorsoft/capacitor-background-geolocation @transistorsoft/capacitor-background-fetch --save`
7.  `npx cap sync`

## Context
I have an application where I want to track a users running training. To get that working in the background I want to test your plugin. Accidentally I can't install the plugin.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
m8xp0w3r@M1-Pro runstm :$ npx cap sync
✔ Copying web assets from www to ios/App/App/public in 439.89ms
✔ Creating capacitor.config.json in ios/App/App in 712.83μs
(node:51336) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/m8xp0w3r/runstm/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ copy ios in 457.54ms
✔ Updating iOS plugins in 3.50ms
[info] Found 6 Capacitor plugins for ios:
       @capacitor/app@1.1.1
       @capacitor/haptics@1.1.4
       @capacitor/keyboard@1.2.2
       @capacitor/status-bar@1.0.8
       @transistorsoft/capacitor-background-fetch@0.0.6
       @transistorsoft/capacitor-background-geolocation@4.4.6
✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] Analyzing dependencies
        objc[51369]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib
        (0x21c9ddeb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
        (0x1086e44f8). One of the two will be used. Which one is undefined.
        objc[51369]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both
        /usr/lib/libauthinstall.dylib (0x21c9ddf00) and
        /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1086e4548).
        One of the two will be used. Which one is undefined.
        objc[51369]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib
        (0x21c9ddf50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
        (0x1086e4598). One of the two will be used. Which one is undefined.
        objc[51369]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x21c9ddfa0)
        and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
        (0x1086e45e8). One of the two will be used. Which one is undefined.
        objc[51369]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib
        (0x21c9ddff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
        (0x1086e4638). One of the two will be used. Which one is undefined.
        objc[51369]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib
        (0x21c9de040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
        (0x1086e4688). One of the two will be used. Which one is undefined.
        
        ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
        
        ### Command
        
        ```
        /usr/local/bin/pod install
        ```
        
        ### Report
        
        * What did you do?
        
        * What did you expect to happen?
        
        * What happened instead?
        
        
        ### Stack
        
        ```
        CocoaPods : 1.11.3
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
        RubyGems : 3.0.3.1
        Host : macOS 12.3 (21E230)
        Xcode : 13.3 (13E113)
        Git : git version 2.32.0 (Apple Git-132)
        Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
        Repositories : trunk - CDN - https://cdn.cocoapods.org/
        ```
        
        ### Plugins
        
        ```
        cocoapods-deintegrate : 1.0.5
        cocoapods-plugins     : 1.0.0
        cocoapods-search      : 1.0.1
        cocoapods-trunk       : 1.6.0
        cocoapods-try         : 1.2.0
        ```
        
        ### Podfile
        
        ```ruby
        platform :ios, '12.0'
        use_frameworks!
        
        # workaround to avoid Xcode caching of Pods that requires
        # Product -> Clean Build Folder after new Cordova plugins installed
        # Requires CocoaPods 1.6 or newer
        install! 'cocoapods', :disable_input_output_paths => true
        
        def capacitor_pods
        pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
        pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
        pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
        pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
        pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
        pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
        pod 'TransistorsoftCapacitorBackgroundFetch', :path =>
        '../../node_modules/@transistorsoft/capacitor-background-fetch'
        pod 'TransistorsoftCapacitorBackgroundGeolocation', :path =>
        '../../node_modules/@transistorsoft/capacitor-background-geolocation'
        end
        
        target 'App' do
        capacitor_pods
        # Add your Pods here
        end
        ```
        
        ### Error
        
        ```
        LoadError - dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried:
        '/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture
        (have 'x86_64', need 'arm64e')) - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in
        `require'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in
        `require'
        /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
        /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in
        `require'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in
        `require'
        /Library/Ruby/Gems/2.6.0/gems/ethon-0.15.0/lib/ethon.rb:3:in `<top (required)>'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in
        `require'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in
        `require'
        /Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in
        `require'
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in
        `require'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:440:in
        `download_typhoeus_impl_async'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:372:in
        `download_and_save_with_retries_async'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:365:in
        `download_file_async'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:284:in
        `ensure_versions_file_loaded'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:208:in `search'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `block in
        search'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `select'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `search'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:385:in `find_cached_set'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:165:in `search_for'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `each'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by!'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
        /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in
        sort_dependencies'
        /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in
        `with_no_such_dependency_error_handling'
        /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in
        `sort_dependencies'
        /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
        /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in
        `require_nested_dependencies_for'
        /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
        /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
        /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
        /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
        /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block in
        resolve_dependencies'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in
        `resolve_dependencies'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
        /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
        /usr/local/bin/pod:23:in `load'
        /usr/local/bin/pod:23:in `<main>'
        ```
        
        ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
        
        [!] Oh no, an error occurred.
        
        Search for existing GitHub issues similar to yours:
        https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle%2C+0x0009%29%3A+tried%3A+%27%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle%27+%28mach-o+file%2C+but+is+an+incompatible+architecture+%28have+%27x86_64%27%2C+need+%27arm64e%27%29%29+-+%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle&type=Issues
        
        If none exists, create a ticket, with the template displayed above, on:
        https://github.com/CocoaPods/CocoaPods/issues/new
        
        Be sure to first read the contributing guide for details on how to properly submit a ticket:
        https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
        
        Don't forget to anonymize any private data!
        
        Searching for inspections failed: undefined method `map' for nil:NilClass
        Looking for related issues on cocoapods/cocoapods...
        
```

</details>

**Comment by m8xp0w3r** [comment]
I will update this issue later that day. Just wanted to add the logs already.

**Comment by christocracy** [comment]
Have you tried googling your error? 

"LoadError - dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/"

There's nothing in your stacktrace referencing this plugin.

It is most likely related to your dev environment, M1 related.

**Comment by m8xp0w3r** [comment]
[That](https://github.com/CocoaPods/CocoaPods/issues/10287#issuecomment-902354887) worked for me. Sorry for the inconvenience. The problem only occurred when adding your plugin so I thought that the the problem comes from here.
