### ISSUE TITLE
Error "Dependency 'androidx.appcompat:appcompat:1.4.1' requires 'compileSdkVersion' to be set to 31 or higher" after upgrading to 4.5.0 and "Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable" after update to SDK 31.

### ISSUE THREAD

**Issue by eduboxgithub** [transistorsoft/capacitor-background-geolocation#71]
## Your Environment
* Plugin version: 4.5.0
* Platform: Android
* Device OS version: Android 12
* Device manufacturer / model: OnePlus 5T
* Capacitor info (`npx cap doctor`)

```
Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/ios: 3.4.3
  @capacitor/android: 3.4.3

[success] Android looking great! 👌
```

## Expected Behavior
Upgrade to 4.5.0 and be able to compile Android app in Android Studio targeting SDK 30, since Capacitor 3.X have no oficial suporte for version 31.

## Actual Behavior
The build os failing in Android Studio with the error regarding Android build dependencies.

## Steps to Reproduce
1. Upgrade to 4.5.0;
2. Make a capacitor android build;
3. Open Android Studio;
4. Try to build app in Android Studio.

## Debug logs

If I do not change anything, only upgrade de plugin version to 4.5.0 this error happens:

```<!-- Syntax highlighting:  DO NOT REMOVE -->
One or more issues found when checking AAR metadata values:

Dependency 'androidx.appcompat:appcompat:1.4.1' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-30'

Dependency 'androidx.appcompat:appcompat-resources:1.4.1' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-30'

Dependency 'androidx.emoji2:emoji2-views-helper:1.0.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-30'

Dependency 'androidx.emoji2:emoji2:1.0.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-30'

Dependency 'androidx.core:core:1.7.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-30'

Dependency 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-30'

Dependency 'androidx.lifecycle:lifecycle-process:2.4.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-30'

Dependency 'androidx.lifecycle:lifecycle-runtime:2.4.0' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-30'
```

If i change compileSdkVersion and targetSdkVersionto 31 in capacitor new errors occours.
After changing to SDk 31 I also had to change in AndroidManifest "android:exported = true" (https://developer.android.com/guide/topics/manifest/activity-element#exported) but other errors happened after that:

```<!-- Syntax highlighting:  DO NOT REMOVE -->
2022-04-04 20:30:31.993 11088-11249/com.app.apptesting E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:592)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalArgumentException: com.app.apptesting: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.capacitorjs.plugins.localnotifications.LocalNotificationManager.cancelTimerForNotification(LocalNotificationManager.java:402)
        at com.capacitorjs.plugins.localnotifications.LocalNotificationManager.schedule(LocalNotificationManager.java:149)
        at com.capacitorjs.plugins.localnotifications.LocalNotificationsPlugin.schedule(LocalNotificationsPlugin.java:57)
        	... 9 more
    
    
    --------- beginning of crash
2022-04-04 20:30:31.994 11088-11249/com.app.apptesting E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
    Process: com.app.apptesting, PID: 11088
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:601)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:592)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalArgumentException: com.app.apptesting: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.capacitorjs.plugins.localnotifications.LocalNotificationManager.cancelTimerForNotification(LocalNotificationManager.java:402)
        at com.capacitorjs.plugins.localnotifications.LocalNotificationManager.schedule(LocalNotificationManager.java:149)
        at com.capacitorjs.plugins.localnotifications.LocalNotificationsPlugin.schedule(LocalNotificationsPlugin.java:57)
        	... 9 more
2022-04-04 20:30:32.001 11088-11249/com.app.apptesting E/TSLocationManager: [c.t.l.a.BackgroundGeolocation$x0 uncaughtException] 
      ‼️  Uncaught Exception: java.lang.reflect.InvocationTargetException
    {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":0, "batchSync":false,"configUrl":"","debug":true,"deferTime":0,"desiredAccuracy":-1,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableStopDetection":false,"distanceFilter":2,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":-1,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":true,"geofenceProximityRadius":2000,"geofenceTemplate":"","headers":{"Content-Type":"application\/json","Authorization":"Bearer 205b4343-983d-49e9-8103-c3daa23c64d0"},"headlessJobService":"com.app.apptesting.BackgroundGeolocationHeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":2000,"locationsOrderDirection":"ASC","logLevel":2,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"Nofiticações Geográficas","text":"As notificações geográficas encontram-se ativas.","color":"","channelName":"TSLocationManager","smallIcon":"","largeIcon":"","priority":0,"sticky":false,"strings":{},"actions":[]},"params":{"global":{"IdProject":42,"IdPlatform":3,"IdLanguage":1},"device":{"ReceiveNotifications":true,"IdApplication":227,"Platform":"android","DeviceGuid":"","RegId":"eFTgBFKQRmGVm8LSF_d8dD:APA91bFAICYAOx_JolBZISb2VrWgvME-4PoYOjFDXB0Os2rZl4t2f_TwMAd9hRdjKV7Ae2Faz3BCxtQEu5xfg6-nRrQHSBSloC_yGV2Sp1kdLAm2842bif5PwKb4tXwfr-ku9_aDrBcS"}},"persist":true,"persistMode":-1,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":true,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":5,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"https:\/\/smartcms.boldapps.pt\/api\/jsonservice.svc\/geofencing\/event","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":0,"odometer":0,"isFirstBoot":true,"didLaunchInBackground":false,"didDeviceReboot":false}
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:601)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.reflect.InvocationTargetException: null
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:592)
    	... 6 common frames omitted
2022-04-04 20:30:32.001 11088-11249/com.app.apptesting E/TSLocationManager: Caused by: java.lang.IllegalArgumentException: com.app.apptesting: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.capacitorjs.plugins.localnotifications.LocalNotificationManager.cancelTimerForNotification(LocalNotificationManager.java:402)
        at com.capacitorjs.plugins.localnotifications.LocalNotificationManager.schedule(LocalNotificationManager.java:149)
        at com.capacitorjs.plugins.localnotifications.LocalNotificationsPlugin.schedule(LocalNotificationsPlugin.java:57)
    	... 9 common frames omitted
2022-04-04 20:30:32.025 11088-11249/com.app.apptesting I/Process: Sending signal. PID: 11088 SIG: 9
```
</details>

**Comment by christocracy** [comment]
This is compileSdkVersion, not targetSdkVersion.

**Comment by christocracy** [comment]
Post your `android/variables.gradle`

**Comment by eduboxgithub** [comment]
Sorry, I was thinking one thing and wrote another thing. The correct is compileSdkVersion.

My variables.gradle

```
ext {
    minSdkVersion = 21
    compileSdkVersion = 30
    targetSdkVersion = 30
    androidxActivityVersion = '1.2.0'
    androidxAppCompatVersion = '1.2.0'
    androidxCoordinatorLayoutVersion = '1.1.0'
    androidxCoreVersion =  '1.3.2'
    androidxMaterialVersion =  '1.3.0'
    androidxBrowserVersion =  '1.3.0'
    androidxExifInterfaceVersion = '1.3.2'
    firebaseMessagingVersion =  '21.0.1'
    playServicesLocationVersion =  '17.1.0'
    androidxFragmentVersion = '1.3.0'
    junitVersion =  '4.13.1'
    androidxJunitVersion =  '1.1.2'
    androidxEspressoCoreVersion =  '3.3.0'
    cordovaAndroidVersion =  '7.0.0'
    googlePlayServicesLocationVersion = '18.0.0'
    okHttpVersion = '4.9.1'
    localBroadcastManagerVersion = '1.0.0'
}
```

**Comment by christocracy** [comment]
```diff
+ compileSdkVersion = 31
```

It is perfectly ok to *compile* your app with a version *higher than* `targetSdkVersion`

**Comment by eduboxgithub** [comment]
Didn't know that... =/ 

Seems good, build is ok now and app seems to work.

Thank you for your help.

**Comment by alexcroox** [comment]
@christocracy you may want to update your Android setup instructions to increase the recommended compileSdkVersion to 31 as my builds fail on 30 now since v4.5.0 update.

https://github.com/transistorsoft/capacitor-background-geolocation/blob/master/help/INSTALL-ANDROID.md

**Comment by christocracy** [comment]
Yes, I see.  I use the latest always, (32 currently)

**Comment by alexcroox** [comment]
I can't seem to build since changing to 31/32:

```
> Task :capacitor-android:generateReleaseBuildConfig
> Task :capacitor-android:javaPreCompileRelease
> Task :transistorsoft-capacitor-background-geolocation:generateReleaseRFile

> Task :capacitor-android:compileReleaseJavaWithJavac FAILED
An exception has occurred in the compiler (1.8.0_212). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.AssertionError: annotationType(): unrecognized Attribute name MODULE (class com.sun.tools.javac.util.UnsharedNameTable$NameImpl)
	at com.sun.tools.javac.util.Assert.error(Assert.java:133)
```

It seems Capacitor has added support for 31+ but it's not being released until Capacitor v4 https://github.com/ionic-team/capacitor/pull/5351#pullrequestreview-846480970

**Comment by christocracy** [comment]
@alexcroox Show me your `variables.gradle`

**Comment by alexcroox** [comment]
Would you prefer if I raise a new issue to avoid spamming OP?

```
ext {
    minSdkVersion = 21
    compileSdkVersion = 32
    targetSdkVersion = 30
    androidxActivityVersion = '1.2.0'
    androidxAppCompatVersion = '1.2.0'
    androidxCoordinatorLayoutVersion = '1.1.0'
    androidxCoreVersion = '1.3.2'
    androidxFragmentVersion = '1.3.0'
    junitVersion = '4.13.1'
    androidxJunitVersion = '1.1.2'
    androidxEspressoCoreVersion = '3.3.0'
    cordovaAndroidVersion = '7.0.0'
    // capacitor-background-geolocation variables
    googlePlayServicesLocationVersion = '18.0.0'
}
```
